/**
 * Physics tuning presets for the platformer physics lab.
 * Each preset provides parameter overrides that approximate
 * the feel of well-known platformer archetypes.
 *
 * These are directional references, not exact recreations.
 */

export const PRESETS = [
  {
    id: "default",
    name: "Default",
    desc: "Balanced defaults",
    params: {},
  },
  {
    id: "mario",
    name: "Mario-like",
    desc: "Momentum, floaty arcs",
    // jump_height ≈ 179px, time_to_apex ≈ 0.46s, fall_ratio ≈ 1.4
    params: {
      ground_max_speed: 340,
      run_multiplier: 1.5,
      ground_accel: 1500,
      ground_decel: 1800,
      ground_friction: 2000,
      air_max_speed: 340,
      air_accel: 1200,
      air_decel: 1000,
      air_drag: 0,
      gravity_up: 1700,
      gravity_down: 2400,
      terminal_velocity: 800,
      fast_fall_multiplier: 1.2,
      jump_velocity: 780,
      jump_cut_multiplier: 0.3,
      coyote_time: 0.05,
      jump_buffer: 0.05,
      snap_to_ground: 4.0,
      max_step_px: 8.0,
    },
  },
  {
    id: "celeste",
    name: "Celeste-like",
    desc: "Snappy, generous forgiveness",
    // jump_height ≈ 129px, time_to_apex ≈ 0.30s, fall_ratio ≈ 1.5
    params: {
      ground_max_speed: 280,
      ground_accel: 5000,
      ground_decel: 5000,
      ground_friction: 6000,
      run_multiplier: 1.0,
      air_max_speed: 280,
      air_accel: 4000,
      air_decel: 4000,
      air_drag: 0,
      gravity_up: 2800,
      gravity_down: 4200,
      terminal_velocity: 900,
      fast_fall_multiplier: 2.2,
      jump_velocity: 850,
      jump_cut_multiplier: 0.25,
      coyote_time: 0.1,
      jump_buffer: 0.1,
      snap_to_ground: 4.0,
      max_step_px: 8.0,
    },
  },
  {
    id: "meatboy",
    name: "Meat Boy-like",
    desc: "Twitchy, fast, snappy",
    params: {
      ground_max_speed: 400,
      ground_accel: 8000,
      ground_decel: 8000,
      ground_friction: 10000,
      run_multiplier: 1.5,
      air_max_speed: 400,
      air_accel: 6000,
      air_decel: 6000,
      air_drag: 0,
      gravity_up: 3000,
      gravity_down: 4000,
      terminal_velocity: 1500,
      fast_fall_multiplier: 1.5,
      jump_velocity: 700,
      jump_cut_multiplier: 0.3,
      coyote_time: 0.05,
      jump_buffer: 0.08,
      snap_to_ground: 4.0,
      max_step_px: 8.0,
    },
  },
  {
    id: "floaty",
    name: "Floaty",
    desc: "Low gravity, long hang",
    params: {
      ground_max_speed: 220,
      ground_accel: 1500,
      ground_decel: 1500,
      ground_friction: 2000,
      run_multiplier: 1.2,
      air_max_speed: 250,
      air_accel: 1400,
      air_decel: 1000,
      air_drag: 200,
      gravity_up: 600,
      gravity_down: 800,
      terminal_velocity: 400,
      fast_fall_multiplier: 1.2,
      jump_velocity: 350,
      jump_cut_multiplier: 0.5,
      coyote_time: 0.12,
      jump_buffer: 0.1,
      snap_to_ground: 6.0,
      max_step_px: 6.0,
    },
  },
  {
    id: "tight",
    name: "Tight",
    desc: "Precise, minimal float",
    params: {
      ground_max_speed: 300,
      ground_accel: 6000,
      ground_decel: 6000,
      ground_friction: 8000,
      run_multiplier: 1.3,
      air_max_speed: 280,
      air_accel: 2000,
      air_decel: 2000,
      air_drag: 0,
      gravity_up: 2500,
      gravity_down: 3500,
      terminal_velocity: 1200,
      fast_fall_multiplier: 1.5,
      jump_velocity: 620,
      jump_cut_multiplier: 0.3,
      coyote_time: 0.06,
      jump_buffer: 0.08,
      snap_to_ground: 4.0,
      max_step_px: 6.0,
    },
  },
];
